services:
  - type: web
    name: gambot
    env: node
    plan: free
    buildCommand: apt-get update && apt-get install -y ffmpeg && npm install
    startCommand: node index.js
    healthCheckPath: /
    envVars:
      - key: TOKEN
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: DB_PATH
        value: ./data
