const MAX_QUESTION_LEN = 100;

const ANSWERS = [
  // yes / positive
  { text: 'absolutely', reaction: '😭' },
  { text: 'yes yes yes', reaction: '😭' },
  { text: '100% trust', reaction: '😭' },
  { text: 'the vibes are yes', reaction: '😭' },
  { text: 'yessss go for it', reaction: '😭' },
  { text: 'obviously bestie', reaction: '😭' },
  { text: 'lowkey... yeah', reaction: '😭' },
  { text: 'somehow yes', reaction: '😭' },
  { text: 'u got this', reaction: '😭' },
  { text: 'yes but dont get excited', reaction: '😭' },
  { text: 'lets say yes and move on', reaction: '😭' },
  { text: 'for ur sake im saying yes', reaction: '😭' },
  { text: 'against all odds yes', reaction: '🙏' },
  { text: 'i asked the cat, the cat said yes', reaction: '😭' },
  { text: 'the voices said yes', reaction: '😭' },
  { text: 'lucky aura detected', reaction: '😭' },
  { text: "it's giving good luck", reaction: '😭' },
  { text: 'i fear the answer is yes', reaction: '😭' },
  { text: 'maybe if u lock in', reaction: '😭' },
  { text: 'unfortunately yes', reaction: '😭' },
  // no / negative
  { text: 'hell nah', reaction: '☠️' },
  { text: 'absolutely not', reaction: '☠️' },
  { text: 'do NOT do that', reaction: '☠️' },
  { text: 'pls dont', reaction: '☠️' },
  { text: 'coin says yes, i say no', reaction: '☠️' },
  { text: 'not looking good gng', reaction: '☠️' },
  { text: 'yeah ur cooked', reaction: '☠️' },
  { text: 'we might be cooked', reaction: '😭' },
  { text: 'terrible news gng', reaction: '💔' },
  { text: 'pack it up', reaction: '☠️' },
  { text: 'dont piss me off', reaction: '☠️' },
  { text: 'be serious', reaction: '☠️' },
  { text: 'oh brother', reaction: '☠️' },
  { text: 'not even close', reaction: '☠️' },
  { text: 'u wish', reaction: '☠️' },
  { text: 'its over', reaction: '☠️' },
  { text: 'give up on that one', reaction: '☠️' },
  { text: 'i got bad news', reaction: '💔' },
  { text: 'the answer was no before u even asked', reaction: '☠️' },
  { text: 'i checked twice. still no', reaction: '☠️' },
  { text: 'ur not gonna like the answer', reaction: '💔' },
  { text: 'i was gonna say yes then i thought about it', reaction: '☠️' },
  { text: 'i asked around. its not looking good', reaction: '💔' },
  { text: 'my sources said absolutely not', reaction: '☠️' },
  { text: 'the council said no', reaction: '☠️' },
  { text: 'no and dont ask why', reaction: '☠️' },
  { text: 'not in this economy', reaction: '😭' },
  { text: 'ur chances are fighting for their life', reaction: '😭' },
  { text: 'its looking historically bad', reaction: '💔' },
  { text: 'the math is disrespectful', reaction: '☠️' },
  { text: 'i wouldnt bet on it', reaction: '☠️' },
  { text: 'i WOULD bet against it', reaction: '☠️' },
  { text: 'nice try', reaction: '☠️' },
  { text: 'not with that attitude', reaction: '☠️' },
  { text: 'this changed nothing. ur still cooked', reaction: '☠️' },
  // maybe / uncertain
  { text: 'probably', reaction: '😭' },
  { text: '50/50 bestie', reaction: '😭' },
  { text: 'depends on ur sleep schedule', reaction: '😭' },
  { text: 'bro i dont know', reaction: '😭' },
  { text: 'the math says maybe', reaction: '😭' },
  { text: 'ask ur lawyer', reaction: '😭' },
  { text: 'ask ur rubber duck', reaction: '😭' },
  { text: 'ask again when im awake', reaction: '😭' },
  { text: 'ask again after the character development', reaction: '☠️' },
  { text: 'give it 5 business days', reaction: '😭' },
  { text: 'try again after a snack', reaction: '😭' },
  { text: 'im legally required to say maybe', reaction: '😭' },
  { text: 'perhaps unfortunately', reaction: '😭' },
  { text: 'allegedly', reaction: '⁉️' },
  { text: 'maybe but keep that to urself', reaction: '😭' },
  // diabolical / roast
  { text: 'im not answering that', reaction: '☠️' },
  { text: 'delete this', reaction: '☠️' },
  { text: 'why would u ask me this', reaction: '😭' },
  { text: 'we both know the answer', reaction: '😭' },
  { text: 'lets not do this', reaction: '😭' },
  { text: 'idk but im judging u', reaction: '☠️' },
  { text: 'dont involve me in this', reaction: '☠️' },
  { text: 'im staying neutral for legal reasons', reaction: '😭' },
  { text: 'the allegations are looking strong', reaction: '☠️' },
  { text: 'this is above my pay grade', reaction: '😭' },
  { text: 'im on ur side but no', reaction: '☠️' },
  { text: 'ur confidence is inspiring', reaction: '😭' },
  { text: 'thats a crazy thing to ask publicly', reaction: '☠️' },
  { text: 'interesting theory', reaction: '😭' },
  { text: 'id delete this question personally', reaction: '☠️' },
  { text: 'lets keep that thought private', reaction: '😭' },
  { text: 'that shouldve stayed in drafts', reaction: '☠️' },
  { text: 'some questions dont need answers', reaction: '😭' },
  { text: 'we couldve gone all day without asking this', reaction: '☠️' },
  { text: 'ur setting me up', reaction: '⁉️' },
  { text: 'my lawyer told me not to answer', reaction: '😭' },
  { text: 'leave my name out of this', reaction: '☠️' },
  { text: 'u did NOT hear this from me', reaction: '🤞' },
  { text: 'im not getting cancelled with u', reaction: '☠️' },
  { text: 'who let bro ask questions', reaction: '⁉️' },
  { text: 'permission to never answer this again', reaction: '😭' },
  { text: 'i miss who i was before reading this', reaction: '😭' },
  { text: 'respectfully what', reaction: '⁉️' },
  { text: 'thats between u and god', reaction: '😭' },
  { text: 'this question ruined my day', reaction: '😭' },
  { text: 'u already know bro', reaction: '😭' },
  // absurd / unhelpful
  { text: 'the magic ball glitched', reaction: '😭' },
  { text: 'i forgot the question already', reaction: '😭' },
  { text: 'im pretending i didnt hear that', reaction: '😭' },
  { text: 'ask the turtle outside', reaction: '😭' },
  { text: 'go touch grass first', reaction: '😭' },
  { text: 'the oven said no', reaction: '😭' },
  { text: 'battery levels too low to answer', reaction: '😭' },
  { text: 'the fridge is humming yes', reaction: '😭' },
  { text: 'in another universe maybe', reaction: '😭' },
  { text: 'case closed', reaction: '☠️' },
  { text: 'sentence: cooked', reaction: '☠️' },
  { text: 'the jury laughing bro', reaction: '☠️' },
  { text: 'delete the evidence', reaction: '☠️' },
  { text: 'source?', reaction: '⁉️' },
  { text: 'according to absolutely nobody', reaction: '⁉️' },
  { text: 'u might wanna sit down', reaction: '💔' },
  { text: 'dont shoot the messenger', reaction: '😭' },
  { text: 'i have information that could ruin ur day', reaction: '☠️' },
  { text: 'ur on ur own with this one', reaction: '😭' },
];

module.exports = {
  name: '8ball',
  helpCategory: 'Fun',
  helpArgs: '<question>',
  description: 'silly magic answers — alias `v 8b <question>`',
  aliases: ['8b', 'eightball', 'ball'],
  ANSWERS,
  execute(message, args) {
    let question = args.join(' ').trim();

    if (!question.replace(/[?\s]+$/g, '').trim()) {
      return message.reply({ content: 'ask something 😭', allowedMentions: { repliedUser: false } });
    }

    if (question.length > MAX_QUESTION_LEN) {
      question = question.slice(0, MAX_QUESTION_LEN).trimEnd() + '…';
    }

    const pick = ANSWERS[Math.floor(Math.random() * ANSWERS.length)];

    message.reply({ content: pick.text, allowedMentions: { repliedUser: false } })
      .then(sent => sent.react(pick.reaction).catch(() => {}))
      .catch(() => {});
  },
};